### ISSUE TITLE
Problem adding this library as a dependency

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-ktx#13]
There is an issue with including this library by itself where classes are not able to be found at runtime. Stacktrace:

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.maps.android.SphericalUtil" on path: DexPathList[[zip file "/data/app/com.google.codelabs.findlocalplacesinar-IlY-Zx_cOMFwQ5RPtmGgug==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.codelabs.findlocalplacesinar-IlY-Zx_cOMFwQ5RPtmGgug==/lib/x86, /data/app/com.google.codelabs.findlocalplacesinar-IlY-Zx_cOMFwQ5RPtmGgug==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

My `build.gradle` looks like this:

```
dependencies {
    implementation 'com.google.maps.android:maps-utils-ktx:0.1.1'
}
```

PR #10 was meant to solve this but looks like there are still issues.

**Comment by barbeau** [comment]
@arriolac In the java lib, the packaging config in `gradle-mvn-push.gradle` looks like this:

~~~
            afterEvaluate {
                artifact bundleReleaseAar
                artifact sourcesJar
                artifact javadocJar
            }
~~~

In this project, it looks like this:

~~~
                afterEvaluate {
                    artifact "$buildDir/outputs/aar/$project.name-release.aar"
                    artifact dokkaJar
                    artifact sourcesJar
                }
~~~

Maybe `artifact "$buildDir/outputs/aar/$project.name-release.aar"` should just be `artifact bundleReleaseAar`?

**Comment by arriolac** [comment]
Hmm I did try that originally but remember it not working. Let me give that a shot and circle back. Thanks @barbeau

**Comment by kafumi** [comment]
@arriolac The issue is reproduced on my app project. I consider the classes from maps-utils-ktx can be loaded as expected but ones from android-maps-utils can not be found at runtime. It looks caused because android-maps-utils is not defined as the dependency of maps-utils-ktx on POM.
https://search.maven.org/artifact/com.google.maps.android/maps-utils-ktx/0.1.1/aar

**Comment by arriolac** [comment]
Thanks @kafumi. Will address this today
